services:
  webserver:
    build: webserver/
    container_name: server/
    ports: 
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres:17
    container_name: postgres_db
    volumes:
     - db:/var/lib/postgresql/data/
     - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: db
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s