services:

  videorecorder:
    build: videostorage/
    container_name: video_storage
    depends_on:
      redisserver:
        condition: service_healthy
        restart: true
    volumes:
      - shared_videos:/app/videos

  redisserver:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  proxy:
    build: proxy/
    container_name: proxy_server
    ports:
      - 50051:50051
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redisserver:
        condition: service_healthy
        restart: true

  webserver:
    build: webserver/
    container_name: server
    ports:
      - 443:443
    extra_hosts: ["host.docker.internal:host-gateway"]
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redisserver:
        condition: service_healthy
        restart: true
    volumes:
      - shared_videos:/app/videos:ro

  db:
    image: postgres:17
    container_name: postgres_db
    volumes:
     - db:/var/lib/postgresql/data/
     - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: db
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  db:
  shared_videos:
    driver: local