services:
  # webserver:
  #   build: webserver/
  #   container_name: server
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #       restart: true

  # core:
  #   build: core/
  #   container_name: core
  #   env_file: "core/.env"
  #   ports:
  #     - 3000:3000
    # volumes:
    #   - /dev/video0:/dev/video0
    # devices:
    #   - "/dev/video0:/dev/video0"
    #   - "/dev/video2:/dev/video2"
    # depends_on:
    #   webserver:
    #     condition: service_healthy
    #     restart: true

  db:
    image: postgres:17
    container_name: bs_postgres_db
    env_file: "core/.env"
    volumes:
     - db:/var/lib/postgresql/data/
     - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432 # to remove after dev
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  db: